CREATE TABLE transactionoutputs (
	Id bigint PRIMARY KEY IDENTITY(1,1),
	TxHash char(64) NOT NULL,
	Blocktime bigint NOT NULL,
	Blockhash char(64) NOT NULL,
	OutValue float NOT NULL,
	OutType varchar(MAX) NOT NULL,
	OutAsm varchar(MAX) NOT NULL,
	OutHex varchar(MAX) NOT NULL,
	Protocol varchar(MAX),
	FileHeader varchar(MAX)
);

CREATE TABLE frequencyanalysis (
	Id bigint PRIMARY KEY IDENTITY(1,1),
	DataDay date NOT NULL UNIQUE,
	NullData int NOT NULL,
	P2PK int NOT NULL,
	P2PKH int NOT NULL,
	P2MS int NOT NULL,
	P2SH int NOT NULL,
	UnknownType int NOT NULL
);

CREATE TABLE sizeanalysis (
	Id bigint PRIMARY KEY IDENTITY(1,1),
	DataDay date NOT NULL,
	AvgSize int NOT NULL,
	Outputs int NOT NULL
);

CREATE TABLE fileanalysis (
	Id bigint PRIMARY KEY IDENTITY(1,1),
	DataDay date NOT NULL,
	avi_wav int NOT NULL,
    bin_file int NOT NULL,
    bpg int NOT NULL,
    bz2 int NOT NULL,
    crx int NOT NULL,
    dat int NOT NULL,
    deb int NOT NULL,
    doc_xls_ppt int NOT NULL,
    docx_xlsx_pptx int NOT NULL,
    dmg int NOT NULL,
    exe_dll int NOT NULL,
    flac int NOT NULL,
    flv int NOT NULL,
    gif int NOT NULL,
    gz int NOT NULL,
    iso int NOT NULL,
    jpg int NOT NULL,
    lz int NOT NULL,
    mkv int NOT NULL,
    mp3 int NOT NULL,
    mp4 int NOT NULL,
    ogg int NOT NULL,
    pdf int NOT NULL,
    png int NOT NULL,
    psd int NOT NULL,
    rar int NOT NULL,
    rtf int NOT NULL,
    seven_z int NOT NULL,
    sqlite int NOT NULL,
    tar int NOT NULL,
    threegp int NOT NULL,
    tiff int NOT NULL,
    webp int NOT NULL,
    wmv int NOT NULL,
    xml int NOT NULL,
    zip int NOT NULL
);

CREATE TABLE protocolanalysis (
	Id bigint PRIMARY KEY IDENTITY(1,1),
	DataDay date NOT NULL,
	Ascribe int NOT NULL,
	Bitproof int NOT NULL,
	BlockaiBindedPixsy int NOT NULL,
	Blocksign int NOT NULL,
	BlockstoreBlockstack int NOT NULL,
	Chainpoint int NOT NULL,
	Coinspark int NOT NULL,
	Colu int NOT NULL,
	Counterparty int NOT NULL,
	CounterpartyTest int NOT NULL,
	CryptoCopyright int NOT NULL,
	Diploma int NOT NULL,
	Emptytx int NOT NULL,
	EternityWall int NOT NULL,
	Factom int NOT NULL,
	LaPreuve int NOT NULL,
	Monegraph int NOT NULL,
	Omni int NOT NULL,
	OpenAssets int NOT NULL,
	Openchain int NOT NULL,
	OriginalMy int NOT NULL,
	ProofOfExistence int NOT NULL,
	ProveBit int NOT NULL,
	Remembr int NOT NULL,
	SmartBit int NOT NULL,
	Stampd int NOT NULL,
	Stampery int NOT NULL,
	UniversityOfNicosia int NOT NULL,
	UnknownProtocol int NOT NULL,
	VeriBlock int NOT NULL
);